# Conditional Copy Files for RM8pro_TONEMAP
ifeq ($(RM8pro_TONEMAP),true)
PRODUCT_COPY_FILES += \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param9.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param9.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut6:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut6 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param6.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param6.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut1:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut1 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param12.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param12.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut9:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut9 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut17:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut17 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut9:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut9 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param1.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param1.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut18:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut18 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut11:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut11 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut10:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut10 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut4:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut4 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut8:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut8 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param0.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param0.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut10:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut10 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param10.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param10.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut2:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut2 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut15:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut15 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut6:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut6 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param4.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param4.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param14.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param14.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut7:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut7 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param16.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param16.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param2.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param2.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut4:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut4 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut3:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut3 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param17.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param17.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param3.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param3.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param15.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param15.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut12:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut12 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut5:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut5 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut13:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut13 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut2:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut2 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut5:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut5 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param8.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param8.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut18:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut18 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/frameSet.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/frameSet.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut15:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut15 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut14:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut14 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut7:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut7 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param5.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param5.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param11.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param11.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param7.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param7.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/photoSet.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/photoSet.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut8:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut8 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut14:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut14 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut13:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut13 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param18.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param18.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut0:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut0 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut16:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut16 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut12:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut12 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut11:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut11 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut3:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut3 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/param13.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/param13.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut0:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut0 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut17:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut17 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/colorLut1:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/colorLut1 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/sceneList.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/sceneList.txt \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/platformSet.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/platformSet.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/default/curveLut16:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/default/curveLut16 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param9.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param9.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut6:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut6 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param6.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param6.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut1:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut1 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param12.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param12.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut9:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut9 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut17:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut17 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut9:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut9 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param1.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param1.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut18:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut18 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut11:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut11 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut10:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut10 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut4:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut4 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut8:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut8 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param0.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param0.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut10:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut10 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param10.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param10.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut2:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut2 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut15:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut15 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut6:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut6 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param4.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param4.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param14.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param14.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut7:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut7 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param16.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param16.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param2.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param2.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut4:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut4 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut3:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut3 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param17.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param17.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param3.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param3.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param15.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param15.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut12:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut12 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut5:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut5 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut13:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut13 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut2:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut2 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut5:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut5 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param8.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param8.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut18:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut18 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/frameSet.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/frameSet.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut15:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut15 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut14:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut14 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut7:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut7 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param5.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param5.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param11.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param11.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param7.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param7.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/photoSet.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/photoSet.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut8:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut8 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut14:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut14 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut13:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut13 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param18.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param18.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut0:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut0 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut16:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut16 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut12:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut12 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut11:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut11 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut3:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut3 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/param13.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/param13.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut0:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut0 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut17:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut17 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/colorLut1:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/colorLut1 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/sceneList.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/sceneList.txt \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/platformSet.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/platformSet.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/normal/curveLut16:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/normal/curveLut16 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param9.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param9.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut6:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut6 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param6.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param6.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut1:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut1 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param12.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param12.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut9:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut9 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut17:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut17 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut9:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut9 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param1.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param1.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut18:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut18 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut11:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut11 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut10:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut10 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut4:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut4 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut8:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut8 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param0.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param0.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut10:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut10 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param10.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param10.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut2:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut2 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut15:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut15 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut6:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut6 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param4.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param4.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param14.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param14.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut7:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut7 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param16.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param16.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param2.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param2.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut4:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut4 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut3:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut3 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param17.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param17.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param3.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param3.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param15.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param15.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut12:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut12 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut5:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut5 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut13:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut13 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut2:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut2 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut5:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut5 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param8.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param8.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut18:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut18 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/frameSet.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/frameSet.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut15:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut15 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut14:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut14 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut7:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut7 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param5.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param5.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param11.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param11.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param7.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param7.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/photoSet.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/photoSet.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut8:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut8 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut14:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut14 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut13:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut13 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param18.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param18.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut0:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut0 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut16:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut16 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut12:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut12 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut11:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut11 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut3:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut3 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/param13.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/param13.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut0:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut0 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut17:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut17 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/colorLut1:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/colorLut1 \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/sceneList.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/sceneList.txt \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/platformSet.ini:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/platformSet.ini \
    vendor/realmeme_cam_mod/extras/RM8pro_TONEMAP/system/vendor/etc/camera/pf/PerfectColorSet/portrait/curveLut16:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pf/PerfectColorSet/portrait/curveLut16 \

endif
