package com.android.internal.org.bouncycastle.asn1.bc;

import com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier;
import com.oplus.uifirst.IOplusUIFirstManager;

/* loaded from: classes4.dex */
public interface BCObjectIdentifiers {
    public static final ASN1ObjectIdentifier bc;
    public static final ASN1ObjectIdentifier bc_ext;
    public static final ASN1ObjectIdentifier bc_pbe;
    public static final ASN1ObjectIdentifier bc_pbe_sha1;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes128_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes192_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes256_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs5;
    public static final ASN1ObjectIdentifier bc_pbe_sha224;
    public static final ASN1ObjectIdentifier bc_pbe_sha256;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes128_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes192_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes256_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs5;
    public static final ASN1ObjectIdentifier bc_pbe_sha384;
    public static final ASN1ObjectIdentifier bc_pbe_sha512;
    public static final ASN1ObjectIdentifier bc_sig;
    public static final ASN1ObjectIdentifier linkedCertificate;
    public static final ASN1ObjectIdentifier qTESLA;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_I;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_III_size;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_III_speed;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_p_I;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_p_III;
    public static final ASN1ObjectIdentifier qTESLA_p_I;
    public static final ASN1ObjectIdentifier qTESLA_p_III;
    public static final ASN1ObjectIdentifier xmss;
    public static final ASN1ObjectIdentifier xmss_SHA256;
    public static final ASN1ObjectIdentifier xmss_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_SHA512;
    public static final ASN1ObjectIdentifier xmss_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_SHAKE256ph;
    public static final ASN1ObjectIdentifier xmss_mt;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256ph;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHA256;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHA512;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_with_SHA256;
    public static final ASN1ObjectIdentifier xmss_with_SHA512;
    public static final ASN1ObjectIdentifier xmss_with_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_with_SHAKE256;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.6.1.4.1.22554");
        bc = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch = aSN1ObjectIdentifier.branch(IOplusUIFirstManager.APP_START_ANIMATION);
        bc_pbe = aSN1ObjectIdentifierBranch;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch2 = aSN1ObjectIdentifierBranch.branch(IOplusUIFirstManager.APP_START_ANIMATION);
        bc_pbe_sha1 = aSN1ObjectIdentifierBranch2;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch3 = aSN1ObjectIdentifierBranch.branch("2.1");
        bc_pbe_sha256 = aSN1ObjectIdentifierBranch3;
        bc_pbe_sha384 = aSN1ObjectIdentifierBranch.branch("2.2");
        bc_pbe_sha512 = aSN1ObjectIdentifierBranch.branch("2.3");
        bc_pbe_sha224 = aSN1ObjectIdentifierBranch.branch("2.4");
        bc_pbe_sha1_pkcs5 = aSN1ObjectIdentifierBranch2.branch(IOplusUIFirstManager.APP_START_ANIMATION);
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch4 = aSN1ObjectIdentifierBranch2.branch(IOplusUIFirstManager.APP_EXIT_ANIMATION);
        bc_pbe_sha1_pkcs12 = aSN1ObjectIdentifierBranch4;
        bc_pbe_sha256_pkcs5 = aSN1ObjectIdentifierBranch3.branch(IOplusUIFirstManager.APP_START_ANIMATION);
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch5 = aSN1ObjectIdentifierBranch3.branch(IOplusUIFirstManager.APP_EXIT_ANIMATION);
        bc_pbe_sha256_pkcs12 = aSN1ObjectIdentifierBranch5;
        bc_pbe_sha1_pkcs12_aes128_cbc = aSN1ObjectIdentifierBranch4.branch("1.2");
        bc_pbe_sha1_pkcs12_aes192_cbc = aSN1ObjectIdentifierBranch4.branch("1.22");
        bc_pbe_sha1_pkcs12_aes256_cbc = aSN1ObjectIdentifierBranch4.branch("1.42");
        bc_pbe_sha256_pkcs12_aes128_cbc = aSN1ObjectIdentifierBranch5.branch("1.2");
        bc_pbe_sha256_pkcs12_aes192_cbc = aSN1ObjectIdentifierBranch5.branch("1.22");
        bc_pbe_sha256_pkcs12_aes256_cbc = aSN1ObjectIdentifierBranch5.branch("1.42");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch6 = aSN1ObjectIdentifier.branch(IOplusUIFirstManager.APP_EXIT_ANIMATION);
        bc_sig = aSN1ObjectIdentifierBranch6;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch7 = aSN1ObjectIdentifierBranch6.branch(IOplusUIFirstManager.APP_EXIT_ANIMATION);
        xmss = aSN1ObjectIdentifierBranch7;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch8 = aSN1ObjectIdentifierBranch7.branch(IOplusUIFirstManager.APP_START_ANIMATION);
        xmss_SHA256ph = aSN1ObjectIdentifierBranch8;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch9 = aSN1ObjectIdentifierBranch7.branch(IOplusUIFirstManager.APP_EXIT_ANIMATION);
        xmss_SHA512ph = aSN1ObjectIdentifierBranch9;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch10 = aSN1ObjectIdentifierBranch7.branch("3");
        xmss_SHAKE128ph = aSN1ObjectIdentifierBranch10;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch11 = aSN1ObjectIdentifierBranch7.branch(IOplusUIFirstManager.LAUNCHER_SI_START);
        xmss_SHAKE256ph = aSN1ObjectIdentifierBranch11;
        xmss_SHA256 = aSN1ObjectIdentifierBranch7.branch("5");
        xmss_SHA512 = aSN1ObjectIdentifierBranch7.branch("6");
        xmss_SHAKE128 = aSN1ObjectIdentifierBranch7.branch("7");
        xmss_SHAKE256 = aSN1ObjectIdentifierBranch7.branch("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch12 = aSN1ObjectIdentifierBranch6.branch("3");
        xmss_mt = aSN1ObjectIdentifierBranch12;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch13 = aSN1ObjectIdentifierBranch12.branch(IOplusUIFirstManager.APP_START_ANIMATION);
        xmss_mt_SHA256ph = aSN1ObjectIdentifierBranch13;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch14 = aSN1ObjectIdentifierBranch12.branch(IOplusUIFirstManager.APP_EXIT_ANIMATION);
        xmss_mt_SHA512ph = aSN1ObjectIdentifierBranch14;
        xmss_mt_SHAKE128ph = aSN1ObjectIdentifierBranch12.branch("3");
        xmss_mt_SHAKE256ph = aSN1ObjectIdentifierBranch12.branch(IOplusUIFirstManager.LAUNCHER_SI_START);
        xmss_mt_SHA256 = aSN1ObjectIdentifierBranch12.branch("5");
        xmss_mt_SHA512 = aSN1ObjectIdentifierBranch12.branch("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch15 = aSN1ObjectIdentifierBranch12.branch("7");
        xmss_mt_SHAKE128 = aSN1ObjectIdentifierBranch15;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch16 = aSN1ObjectIdentifierBranch12.branch("8");
        xmss_mt_SHAKE256 = aSN1ObjectIdentifierBranch16;
        xmss_with_SHA256 = aSN1ObjectIdentifierBranch8;
        xmss_with_SHA512 = aSN1ObjectIdentifierBranch9;
        xmss_with_SHAKE128 = aSN1ObjectIdentifierBranch10;
        xmss_with_SHAKE256 = aSN1ObjectIdentifierBranch11;
        xmss_mt_with_SHA256 = aSN1ObjectIdentifierBranch13;
        xmss_mt_with_SHA512 = aSN1ObjectIdentifierBranch14;
        xmss_mt_with_SHAKE128 = aSN1ObjectIdentifierBranch15;
        xmss_mt_with_SHAKE256 = aSN1ObjectIdentifierBranch16;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch17 = aSN1ObjectIdentifierBranch6.branch(IOplusUIFirstManager.LAUNCHER_SI_START);
        qTESLA = aSN1ObjectIdentifierBranch17;
        qTESLA_Rnd1_I = aSN1ObjectIdentifierBranch17.branch(IOplusUIFirstManager.APP_START_ANIMATION);
        qTESLA_Rnd1_III_size = aSN1ObjectIdentifierBranch17.branch(IOplusUIFirstManager.APP_EXIT_ANIMATION);
        qTESLA_Rnd1_III_speed = aSN1ObjectIdentifierBranch17.branch("3");
        qTESLA_Rnd1_p_I = aSN1ObjectIdentifierBranch17.branch(IOplusUIFirstManager.LAUNCHER_SI_START);
        qTESLA_Rnd1_p_III = aSN1ObjectIdentifierBranch17.branch("5");
        qTESLA_p_I = aSN1ObjectIdentifierBranch17.branch("11");
        qTESLA_p_III = aSN1ObjectIdentifierBranch17.branch("12");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch18 = aSN1ObjectIdentifier.branch(IOplusUIFirstManager.LAUNCHER_SI_START);
        bc_ext = aSN1ObjectIdentifierBranch18;
        linkedCertificate = aSN1ObjectIdentifierBranch18.branch(IOplusUIFirstManager.APP_START_ANIMATION);
    }
}
